### ISSUE TITLE
Added postgres 9.6 support

### ISSUE THREAD

**Issue by marteinn** [marteinn/postgres-backup-restore-s3#2]

**Comment by dchersey** [comment]
Hi, is there any plan to update this to support 9.6?

**Comment by marteinn** [comment]
Hi @dchersey!

Thanks for reminding me of this repo :) I just pushed out a new release 93ecff5bcc7d4c25bd8f6a031154b831bc5df457 that adds both postgres 9.6 and 10 support.

Please try it out and let me know if you experience any issues.

**Comment by dchersey** [comment]
Terrific, thank you!  And thank you for this very useful container. 

 FYI, I have created a docker-compose file that incorporates this into a full server stack, triggered daily using the basic crond service built into alpine/busybox. 

If it's interesting to you, I can contribute it to the repo.

**Comment by marteinn** [comment]
I think examples are always appreciated (I think a lot of docker image repos miss out on this). Perhaps you can do I a PR and we go from there?

My own use case is really simple, I just have a dedicated docker-compose task that I run in cron outside docker:

```
# crontab
# Backup database daily
0 0 * * * /usr/local/bin/docker-compose -f /home/user/app/docker-compose-prod-backup.yml run --rm db_backup
```
